# Generated by Django 4.1.7 on 2023-04-28 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 28, 17, 25, 33, 741398, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
